version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      DIFFICULTY: "normal"
      SERVER_NAME: "Server DDD"
#      TYPE: "CURSEFORGE"
#      CF_SERVER_MOD: "/modpacks/name_of_modpack.zip"
#      WORLD: "/worlds/basic"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
      - ./worlds:/worlds:ro
      - ./modpacks:/modpacks
      - ./mods:/data/mods
      - ./plugins:/data/plugins